[plugin]
id = "websocket-compiler-plugin"
class = "io.ballerina.stdlib.websocket.plugin.WebSocketCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/websocket-compiler-plugin-@project.version@.jar"

[[dependency]]
path = "../native/build/libs/websocket-native-@project.version@.jar"

[[dependency]]
path = "./lib/http-native-@stdlib.httpnative.version@.jar"
